// <auto-generated />
namespace CombisApp.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial22333 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial22333));
        
        string IMigrationMetadata.Id
        {
            get { return "201710191435440_initial22333"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
